services:
  backup-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - REPO_URL=${https://github.com/Anveshith/cicd-repo-backup-system}
      - BACKUP_DIR=/backups
      - GPG_PASSPHRASE=${MyBackupVault!2026}
    volumes:
      - ../backups:/backups

  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: bash -c "pytest /app/tests/ -v --tb=short"
    environment:
      - GPG_PASSPHRASE=${MyBackupVault!2026}
      - BACKUP_DIR=/backups
    volumes:
      - ../backups:/backups